# Use container-based infrastructure
sudo: false
language: scala
jdk: oraclejdk8
scala:
  - 2.11.11
  - 2.12.3
script:
  - sbt ++$TRAVIS_SCALA_VERSION 'testOnly *InstanceTypes *RegionAliases'
notifications:
  email: false
  webhooks:
    urls: https://webhooks.gitter.im/e/2ea1cb632092a05398fb
    on_success: change
    on_failure: always
    on_start: never
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
